### ISSUE TITLE
yaml2json misses underscores in certain strings

### ISSUE THREAD

**Issue by astefanova** [bronze1man/yaml2json#12]
It seems the issue is only reproducible for *certain* strings. 
The pattern **\<number\>\<string\>\<underscore\>\<number\>** is faulty. 
There may be more.

See:
```bash
$ cat file.yml
---
property: 0testS_1value
###
$ cat file.yml | yaml2json
{"property":"0testS1value"}
```

**Comment by bronze1man** [comment]
I can confirm this bug. 
And it is come from the library of yaml  https://github.com/go-yaml/yaml

**Comment by bronze1man** [comment]
This issues is fixed and add a test to ensure it will be fixed in the future.
Thanks for your report again.

https://github.com/bronze1man/yaml2json/blob/master/y2jLib/lib_test.go#L24
