### ISSUE TITLE
Build with go to > 1.19 because of critical vulnerabilities in older go libraries (stdlib)

### ISSUE THREAD

**Issue by ludimax** [bronze1man/yaml2json#26]
Can you use a newer go version to build this nice tool? Go 1.19 is known for having critical vulnerabilities. I did some minimal testing using Go 1.22 and it seems to work.

**Comment by bronze1man** [comment]
I have rebuild it with go1.23.0 with v1.3.3
Here is the link:
https://github.com/bronze1man/yaml2json/releases/download/v1.3.3/yaml2json_all_go1.23.0.zip

Is it good for you?
