### ISSUE TITLE
Incorrect Version for ARM64 Chip in yaml2json

### ISSUE THREAD

**Issue by shy-stone** [bronze1man/yaml2json#27]
Detailed Description
When attempting to download the yaml2json tool for the ARM64 chip, I found that all downloaded versions are x86-64 files, not ARM architecture files. This results in the tool not working on ARM64 devices.

Steps to Reproduce
Visited the official website or GitHub repository of yaml2json to find the version suitable for the ARM64 chip.
Downloaded multiple versions of the yaml2json file, such as yaml2json-1.0.0-linux-x86_64 and yaml2json-1.1.0-linux-x86_64.
Attempted to run the downloaded files on an ARM64 device, but they did not work, displaying errors like "cannot execute file" or "incorrect format".
Expected Result
I hope to find the correct version for the ARM64 chip in the official resources of yaml2json, or to receive clear instructions on how to install and use the yaml2json tool on an ARM64 device.

Current Issue
All downloaded yaml2json files are x86-64 versions and do not run on ARM64 devices.
The official resources do not provide clear download links or instructions for ARM64 versions.
Environment Information
Operating System: Kylin OS
Chip Architecture: ARM64
Versions of yaml2json tried: 1.3.3
Request for Support
Please provide the following support from the official team:

Provide a download link for the yaml2json version suitable for the ARM64 chip.
If the official team does not provide precompiled ARM64 versions, please provide detailed compilation guidelines so users can compile it themselves.
Update the official documentation to clearly list download links and installation instructions for different architectures.
Thank you for your support!

**Comment by shy-stone** [comment]
file yaml2json_linux_arm64 
yaml2json_linux_arm64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
is x86-64 not ARM aarch64

**Comment by bronze1man** [comment]
Thanks for report. I will dig into it this week.

**Comment by bronze1man** [comment]
https://github.com/bronze1man/yaml2json/releases/tag/v1.3.4
should fix this bug. Please try it .
