### ISSUE TITLE
How to run in linux

### ISSUE THREAD

**Issue by dncmn** [bronze1man/yaml2json#4]
I don't know how to run this project.I have done it in my linux system.

**Comment by golokeshpatra45** [comment]
It does work on linux . I have tried it myself (But it is advisable to install dos2unix and convert the script as per unix scheme).
My Question is , when I am running it as bash (i.e from terminal ) yaml2json works fine.
But when I run the same with the help of java , it says yaml2json command not found. 
Please help me out.

**Comment by bronze1man** [comment]
"it says yaml2json command not found"
It looks like the java can not found that binary file.
You can use the absolute file path of the binary to call it in java.

**Comment by bronze1man** [comment]
Close for none-response after one year.
