### ISSUE TITLE
Running on linux and executing from JAR

### ISSUE THREAD

**Issue by golokeshpatra45** [bronze1man/yaml2json#6]
@bronze1man My Question is , when I am running it as bash (i.e from terminal ) yaml2json works fine.
But when I run the same with the help of java , it says yaml2json command not found. 
Please help me out.

**Comment by bronze1man** [comment]
"it says yaml2json command not found"
It looks like the java can not found that binary file.
You can use the absolute file path of the binary (like /usr/local/bin/yaml2json) to call it in java.

**Comment by bronze1man** [comment]
Close for none-response after one year.
