### ISSUE TITLE
Builds outdated

### ISSUE THREAD

**Issue by mkjois** [bronze1man/yaml2json#7]
Looks like the `builds/` directory is 4 years old. This is a useful tool, could you support or elaborate on how to build this for all those architectures now. Maybe publish builds as Github releases?

**Comment by bronze1man** [comment]
What is your `real` problem?
May be 4 years old is not the problem.
The source code do not have any change since it builded.

You can use golang and set GOARCH and GOOS to cross compile to all the platform golang supported.

**Comment by mkjois** [comment]
The commit history definitely indicates that the source code has changed. Even if they're just improvements and not breaking changes, it would be nice to have the latest builds readily available.

For example, I want to `yaml2json` in my build process, but instead of installing through a package manager or downloading the latest binary, I have to clone the repo and cross compile every time I build! Or I have to manually cross compile and commit both Darwin and Linux binaries to my repo once in a while. Inconvenient at best...

But it's not the end of the world, please let us know if that's the recommended approach here.

**Comment by bronze1man** [comment]
I have added a completed development and build document in the README.md 
Please let me know if you have more problem.
