### ISSUE TITLE
MacOS build is broken on High Sierra (macOS 10.13.2)  

### ISSUE THREAD

**Issue by fogfish** [bronze1man/yaml2json#8]
The binary image supplied with this application is broken on macOS 10.13.2
```
yaml2json
failed MSpanList_Insert 0x201000 0x35b4e88bf768 0x0
fatal error: MSpanList_Insert
```

The rebuild of image with following command fixes an issue.
```
go get -v github.com/bronze1man/yaml2json
```

**Comment by bronze1man** [comment]
Fixed and tested.
Please download new version if you still have this problem. https://github.com/bronze1man/yaml2json/releases
